//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace browserMTH.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://bing.com")]
        public string homePage {
            get {
                return ((string)(this["homePage"]));
            }
            set {
                this["homePage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://xkcd.com")]
        public string userBookmarkOne {
            get {
                return ((string)(this["userBookmarkOne"]));
            }
            set {
                this["userBookmarkOne"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://bing.com")]
        public string userBookmarkTwo {
            get {
                return ((string)(this["userBookmarkTwo"]));
            }
            set {
                this["userBookmarkTwo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://bing.com")]
        public string userBookmarkThree {
            get {
                return ((string)(this["userBookmarkThree"]));
            }
            set {
                this["userBookmarkThree"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://bing.com")]
        public string userBookmarkFour {
            get {
                return ((string)(this["userBookmarkFour"]));
            }
            set {
                this["userBookmarkFour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://bing.com")]
        public string userBookmarkFive {
            get {
                return ((string)(this["userBookmarkFive"]));
            }
            set {
                this["userBookmarkFive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://bing.com")]
        public string userBookmarkSix {
            get {
                return ((string)(this["userBookmarkSix"]));
            }
            set {
                this["userBookmarkSix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://bing.com")]
        public string userBookmarkSeven {
            get {
                return ((string)(this["userBookmarkSeven"]));
            }
            set {
                this["userBookmarkSeven"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://bing.com")]
        public string userBookmarkEight {
            get {
                return ((string)(this["userBookmarkEight"]));
            }
            set {
                this["userBookmarkEight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://bing.com")]
        public string userBookmarkNine {
            get {
                return ((string)(this["userBookmarkNine"]));
            }
            set {
                this["userBookmarkNine"] = value;
            }
        }
    }
}
